# Configuration file to declaratively configure labels
# Ref: https://github.com/EndBug/label-sync#Config-files

- name: area/bucket
  description: Bucket related issues and PRs
  color: '#00b140'
- name: area/git
  description: Git related issues and PRs
  color: '#863faf'
- name: area/helm
  description: Helm related issues and PRs
  color: '#1673b6'
- name: area/oci
  description: OCI related issues and PRs
  color: '#c739ff'
- name: area/storage
  description: Storage related issues and PRs
  color: '#4b0082'
- name: backport:release/v1.0.x
  description: To be backported to release/v1.0.x
  color: '#ffd700'
