name: CIFuzz
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
      - 'MAINTAINERS'

permissions:
  contents: read
  
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
    - name: Setup Go
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version: 1.20.x
        cache-dependency-path: |
          **/go.sum
          **/go.mod
    - name: Smoke test Fuzzers
      run: make fuzz-smoketest
      env:
        SKIP_COSIGN_VERIFICATION: true
